feat(CC-107): create patient endpoint
ItaloRAmaral/cliniccontrol pull request #108
Opened 2023-12-17 19:33 UTC by ItaloRAmaral

# O que foi modificado?

- Substitua este texto por uma descrição breve da modificação. Adicione mais tópicos se julgar necessário;
- Adicione imagens de apoio para auxiliar na avaliação;

### Links de referência e etapas para avaliação

- Acesse o link http://localhost:3000/xxx/dma;
- Clique no botão...;
- Avalie que...;

### Palavras-chave

`Palavra-chave 1`, `Palavra-chave 2`, `Palavra-chave 3`

# Por que foi modificado?

- Substitua este texto por uma descrição breve dos motivos da alteração;
- Adicione os tópicos que julgar necessário;

# Como foi modificado ?

- Substitua este texto por uma descrição breve da abordagem utilizada para implementar a mudança;
- Adicione os tópicos que julgar necessário;

2023-12-20 12:01 UTC, luanavfg requested changes

2023-12-21 10:45 UTC, ItaloRAmaral commented on libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/create-patient.e2e-spec.ts
> +    const patientOnDatabase = await prisma.patient.findUnique({
Qual erro?? Pq aqui pra mim está normal

2023-12-21 12:27 UTC, luanavfg commented on libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/create-patient.e2e-spec.ts
> +    const patientOnDatabase = await prisma.patient.findUnique({
Ficou corrigido depois que você mexeu nos tipos da outra PR.

2023-12-21 18:27 UTC, luanavfg approved these changes

2023-12-21 18:27 UTC, merged